### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by aw-snap** [Benchmaker/PlugBot#1]
Auto DC or !dc command.
😃

**Comment by Benchmaker** [comment]
@aw-snap Hello, thank you for the suggestion I will see what I can do within the next up coming days about a DC command it may take some time though!

**Comment by Benchmaker** [comment]
@aw-snap I've been testing a DC system out its a really basic prototype though so dont expect the DC system to be out plus im very busy with finals and other stuff so sorry if it doesnt happen right away!

**Comment by aw-snap** [comment]
Okay, don't worry! :)

**Comment by Benchmaker** [comment]
@aw-snap but I added roulette cause i felt bad for not adding it DC right away!

**Comment by aw-snap** [comment]
@Benchmaker yea, i saw, and i like new roulette command! :)
